<script>
    tailwind.config = {
        darkMode: 'class',
        theme: {
            extend: {
                colors: {
                    /* Ayoub Jomla App — ayoub_jomla_2 DESIGN.md */
                    primary: '#00450d',
                    'on-primary': '#ffffff',
                    'primary-container': '#1b5e20',
                    'on-primary-container': '#90d689',
                    'primary-fixed': '#acf4a4',
                    'primary-fixed-dim': '#91d78a',
                    'surface-tint': '#2a6b2c',
                    secondary: '#286b33',
                    'on-secondary': '#ffffff',
                    'secondary-container': '#abf4ac',
                    'on-secondary-container': '#2e7238',
                    tertiary: '#5f2c00',
                    'on-tertiary': '#ffffff',
                    'tertiary-container': '#823f00',
                    'on-tertiary-container': '#ffb481',
                    deal: '#f57c00',
                    background: '#f9f9f9',
                    surface: '#f9f9f9',
                    'on-background': '#1a1c1c',
                    'on-surface': '#1a1c1c',
                    'on-surface-variant': '#41493e',
                    'surface-dim': '#dadada',
                    'surface-bright': '#f9f9f9',
                    'surface-container-lowest': '#ffffff',
                    'surface-container-low': '#f3f3f3',
                    'surface-container': '#eeeeee',
                    'surface-container-high': '#e8e8e8',
                    'surface-container-highest': '#e2e2e2',
                    'surface-variant': '#e2e2e2',
                    outline: '#717a6d',
                    'outline-variant': '#c0c9bb',
                    error: '#ba1a1a',
                    'on-error': '#ffffff',
                },
                borderRadius: {
                    DEFAULT: '0.25rem',
                    lg: '0.5rem',
                    xl: '0.75rem',
                    full: '9999px',
                },
                fontFamily: {
                    display: ['Inter', 'sans-serif'],
                    body: ['Inter', 'sans-serif'],
                },
                fontSize: {
                    'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
                    'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
                    'title-lg': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                    'title-md': ['16px', { lineHeight: '24px', fontWeight: '600' }],
                    'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                    'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                    'label-md': ['12px', { lineHeight: '16px', fontWeight: '500' }],
                },
            },
        },
    };
</script>
